

if(`window -exists SYXZ_Master`)
{
	deleteUI SYXZ_Master;
}

else
{
	//string $myScriptsPath = "//samshum-syxz/ab$/Light_Library/Maya/maya/plug-ins/";
	string $myScriptsPath = "https://github.com/SamShum-June/SYXZ_MEL/tree/main/SYXZ_MEL/NO_08/";
	global string $syxztoolsPath;
	$syxztoolsPath=($myScriptsPath+"SYS/");
	eval ("source \""+$syxztoolsPath+"Memu.mel\"");
	SYXZ_Master_window;
}


