

if(`window -exists SYXZ_Master`)
{
	deleteUI SYXZ_Master;
}

else
{
	
	string $myScriptsPath = "https://raw.githubusercontent.com/SamShum-June/SYXZ_MEL/main/SYXZ_MEL/NO_08/";
	global string $syxztoolsPath;
	$syxztoolsPath=($myScriptsPath+"SYS/");
	eval ("source \""+$syxztoolsPath+"Menu.mel\"");
	SYXZ_Index;
}




// string $myScriptsPath = "//samshum-syxz/ab$/Light_Library/Maya/maya/plug-ins/";
